# Initial file created by Alexander Makejkin
# It may not support formats generated by algorithms other than WCA
#
# Finds all .rsf files generated by clusterer and outputs a prettified version as a .txt
# with the same file name, including metadata
#
# How to use: Place this file in the folder containing target .rsf files, then run it with
# python3 prettify_output.py

import os
from argparse import ArgumentParser
from pathlib import Path

strip_index = len("org.apache.lucene.codecs.")


class ClusteringInfo:
    def __init__(self, path):
        clusters = []
        with open(path, "r") as file:
            for line in file:
                # Assumptions:
                # - enumerated from 0 to N in order of lines
                # - always 3 parts per line
                parts = line.strip().split()

                # Cut off common text present in all outputs
                element = parts[2]
                element = element[strip_index:]

                cluster_id = int(parts[1])
                if cluster_id >= len(clusters):
                    clusters.append(set([element]))
                else:
                    clusters[cluster_id].add(element)

        list_lines = []
        for cluster in clusters:
            elements = sorted([element + "\n" for element in cluster])
            list_lines.append(elements)

        list_lines = sorted(list_lines, key=lambda l: (len(l), l))
        self.list_lines = list_lines

    @property
    def total_clusters(self) -> int:
        return len(self.list_lines)

    @property
    def clusters_equal_1(self) -> list[list[int]]:
        return list(filter(lambda x: len(x) == 1, self.list_lines))

    @property
    def clusters_over_1(self) -> list[list[int]]:
        return list(filter(lambda x: len(x) > 1, self.list_lines))

    @property
    def average_size_per_cluster(self) -> float:
        return sum([len(x) for x in self.list_lines]) / self.total_clusters

    def __lt__(self, other):
        return self.total_clusters < other.total_clusters

    def to_csv_line(self) -> str:
        return f"{self.total_clusters},{self.average_size_per_cluster},{len(self.clusters_equal_1)},{len(self.clusters_over_1)},{sum([len(x) for x in self.clusters_over_1]) / len(self.clusters_over_1)},{len(self.clusters_over_1[len(self.clusters_over_1) // 2])},{len(self.clusters_over_1[-1])}\n"

    def __str__(self) -> str:
        result = ""
        result += "### Metadata ###\n"
        result += f"Total number of clusters: {self.total_clusters}\n"
        result += f"Average size per cluster: {self.average_size_per_cluster}\n"
        result += f"Number of clusters of size == 1: {len(self.clusters_equal_1)}\n"
        result += f"Number of clusters of size > 1 : {len(self.clusters_over_1)}\n"
        result += f"Average size per cluster of size > 1: {sum([len(x) for x in self.clusters_over_1]) / len(self.clusters_over_1)}\n"
        result += f"Median size per cluster of size > 1 : {len(self.clusters_over_1[len(self.clusters_over_1) // 2])}\n"
        result += f"Largest cluster size: {len(self.clusters_over_1[-1])}\n"
        result += "################\n"
        result += "Clusters:\n\n"

        for line in self.list_lines:
            cluster_size = len(line)
            if cluster_size > 1:
                result += f"Elements per cluster: {len(line)}\n"
            for item in line:
                result += f"{item}"
            result += "\n"

        return result


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("--csv", type=Path, default=None)
    parser.add_argument("directory", nargs="?", default=os.getcwd())
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    directory = args.directory
    csv = args.csv
    suffix = ".rsf"
    len_suffix = len(suffix)

    combined_data = []

    for file in os.listdir(directory):
        if file.endswith(suffix):
            clustering_info = ClusteringInfo(file)
            with open(f"{file[:-len_suffix]}.txt", "w") as outfile:
                outfile.write(str(clustering_info))
            combined_data.append(clustering_info)

    if csv is not None:
        with open(csv, "w") as csvfile:
            csvfile.write(
                "total_clusters,average_size_per_cluster,num_clusters_equal_1,num_clusters_over_1,average_size_per_cluster_over_1,median_size_per_cluster_over_1,largest_cluster_size\n"
            )
            for clustering_info in sorted(combined_data):
                csvfile.write(clustering_info.to_csv_line())
