# Initial file created by Alexander Makejkin
# It may not support formats generated by algorithms other than WCA
#
# Finds all .rsf files generated by clusterer and outputs a prettified version as a .txt
# with the same file name, including metadata
#
# How to use: Place this file in the folder containing target .rsf files, then run it with
# python3 prettify_output.py

import os

strip_index = len("org.apache.lucene.codecs.")

def get_clusters(path) -> frozenset[frozenset[str]]:
    clusters = []
    with open(path, "r") as file:
        for line in file:
            # Assumptions:
            # - enumerated from 0 to N in order of lines
            # - always 3 parts per line
            parts = line.strip().split()
            
            # Cut off common text present in all outputs
            element = parts[2]
            element = element[strip_index:]

            cluster_id = int(parts[1])
            if cluster_id >= len(clusters):
                clusters.append(set([element]))
            else:
                clusters[cluster_id].add(element)
    return frozenset([frozenset(i) for i in clusters])

def write_file(name, clusters: frozenset[frozenset[str]]):
    with open(name, "w") as outfile:
        list_lines = []
        for cluster in clusters:
            elements = sorted([element + "\n" for element in cluster])
            list_lines.append(elements)
        
        list_lines = sorted(list_lines, key=lambda l: (len(l), l))

        # Metadata
        outfile.write("### Metadata ###\n")

        total_clusters = len(list_lines)
        outfile.write(f"Total number of clusters: {total_clusters}\n")
        outfile.write(f"Average size per cluster: {sum([len(x) for x in list_lines]) / total_clusters}\n")

        clusters_equal_1 = list(filter(lambda x: len(x) == 1, list_lines))
        outfile.write(f"Number of clusters of size == 1: {len(clusters_equal_1)}\n")

        clusters_over_1 = list(filter(lambda x: len(x) > 1, list_lines))
        outfile.write(f"Number of clusters of size > 1 : {len(clusters_over_1)}\n")
        total_clusters = len(clusters_over_1)
        outfile.write(f"Average size per cluster of size > 1: {sum([len(x) for x in clusters_over_1]) / total_clusters}\n")
        outfile.write(f"Median size per cluster of size > 1 : {len(clusters_over_1[len(clusters_over_1) // 2])}\n")
        outfile.write(f"Largest cluster size: {len(clusters_over_1[-1])}\n")
        outfile.write("################\n")
        outfile.write("Clusters:\n\n")

        for line in list_lines:
            cluster_size = len(line)
            if cluster_size > 1: 
                outfile.write(f"Elements per cluster: {len(line)}\n")
            outfile.writelines(line)
            outfile.write("\n")

directory = os.getcwd()
suffix = ".rsf"
len_suffix = len(suffix)

for file in os.listdir(directory):
    if file.endswith(suffix):
        clusters = get_clusters(file)
        write_file(f"{file[:-len_suffix]}.txt", clusters)


